# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aye', models.TextField()),
                ('tarjome', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Published', 'منتشر شده'), ('Draft', 'چک نویس')], default='Draft', max_length=30)),
            ],
        ),
    ]
