# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_profile_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratio',
            field=models.IntegerField(default=10),
        ),
    ]
