# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_date', models.DateTimeField(verbose_name='last edit')),
                ('answer_rate', models.IntegerField(default=0, validators=[quiz.models.Question.valid_rate])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('url_slug', models.SlugField(allow_unicode=True)),
                ('question_date', models.DateTimeField(verbose_name='date submitted')),
                ('question_type', models.CharField(choices=[('MC', 'چند گزینه ای'), ('DES', 'تشریحی'), ('BLK', 'جای خالی'), ('TF', 'صحیح غلط')], default='DES', max_length=20)),
                ('question_rate', models.IntegerField(default=0, validators=[quiz.models.Question.valid_rate])),
                ('question_difficulty', models.IntegerField(default=0, validators=[quiz.models.Question.valid_rate])),
                ('lesson', models.CharField(default='ریاضی', max_length=50, validators=[quiz.models.Question.valid_lessons])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
